export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_SINGLE_USER_REQUEST = "GET_SINGLE_USER_REQUEST";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL";

export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_RESET = "ADD_NEW_PRODUCT_RESET";
export const ADD_NEW_PRODUCT_FAIL = "ADD_NEW_PRODUCT_FAIL";


export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAIL = "UPDATE_STOCK_FAIL";
export const UPDATE_STOCK_RESET = "UPDATE_STOCK_RESET";


export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";


export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const ADD_OUTLET_INFO_REQUEST = "ADD_OUTLET_INFO_REQUEST";
export const ADD_OUTLET_INFO_SUCCESS = "ADD_OUTLET_INFO_SUCCESS";
export const ADD_OUTLET_INFO_RESET = "ADD_OUTLET_INFO_RESET";
export const ADD_OUTLET_INFO_FAIL = "ADD_OUTLET_INFO_FAIL";

export const UPDATE_OUTLET_INFO_REQUEST = "UPDATE_OUTLET_INFO_REQUEST";
export const UPDATE_OUTLET_INFO_SUCCESS = "UPDATE_OUTLET_INFO_SUCCESS";
export const UPDATE_OUTLET_INFO_RESET = "UPDATE_OUTLET_INFO_RESET";
export const UPDATE_OUTLET_INFO_FAIL = "UPDATE_OUTLET_INFO_FAIL";

export const GET_OUTLET_INFO_REQUEST = "GET_OUTLET_INFO_REQUEST";
export const GET_OUTLET_INFO_SUCCESS = "GET_OUTLET_INFO_SUCCESS";
export const GET_OUTLET_INFO_FAIL = "GET_OUTLET_INFO_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
